/*
*********************************************************************************************************
*                                               uC/OS-II
*                                               实时内核
*
*                        (c) Copyright 1992-1998, Jean J. Labrosse, Plantation, FL
*                                               版权所有
*
*                                            MCU-51 专用代码
*                                           KEIL C51大模式编译
*
* 文件名 : INCLUDES.H
* 作者   : Jean J. Labrosse
* 改编   : 杨屹 gdtyy@ri.gdt.com.cn 巨龙公司系统集成开发部 2002.09.27
*********************************************************************************************************
*/

//uC/OS-II核心
#include    <os_cpu.h>
#include    <os_cfg.h>
#include    <ucos_ii.h>

//系统显示
//#include    <serial.h>
#include    <reg51.h>

//用户头文件加在最后面
//Your head file add here.